name: Run Jupyter Notebook

on: [push, pull_request]

jobs:
  run-notebook:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies from requirements.txt
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install MEGAcmd
      run: |
        sudo apt-get update
        sudo apt-get install -y megatools

    - name: Download CSV Files from Mega
      run: |
        megadl 'https://mega.nz/folder/GRMlHbzB#RNCqR2Wn1MwV6UkK4i-8dQ'
        # List the directory structure to verify where the files are
        ls -R

    - name: Move downloaded files to root directory
      run: |
        # Move files to the working directory only if they are not already there
        for file in $(find . -name '*.csv'); do
          if [ "$file" != "./$(basename $file)" ]; then
            mv "$file" . || true
          fi
        done

    # Commented out the notebook execution step
    # - name: Run Jupyter Notebook
    #   run: |
    #     jupyter nbconvert --to notebook --execute --ExecutePreprocessor.timeout=-1 code.ipynb --output executed_notebook.ipynb

    - name: Upload Results
      uses: actions/upload-artifact@v3
      with:
        name: executed_notebook
        path: executed_notebook.ipynb
